### ISSUE TITLE
rollup 配置 eslint 报错

### ISSUE THREAD

**Issue by JangYB** [iwfan/chore-cli#41]
![image](https://user-images.githubusercontent.com/21301544/116640727-ca10f280-a99d-11eb-8f43-3d628824c410.png)

**Comment by iwfan** [comment]
感谢提交 issue，最近主要在做支持 esbuild 的工作。关于 rollup 的配置没有及时更新，预计会在下个版本修复。

**Comment by iwfan** [comment]
rollup 配置已更新，升级 v0.2.1 版本可解决此问题。
